version: "3.8"

services:
  website-ticket:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Peta port 3000 di host ke port 3000 di container
    environment:
      - NODE_ENV=production
    restart: always # Opsional, agar container restart jika ada kegagalan
