apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-ticket
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website-ticket
  template:
    metadata:
      labels:
        app: website-ticket
    spec:
      containers:
        - name: website-ticket
          image: asriazhari/website-ticket:1.0.7
---
apiVersion: v1
kind: Service
metadata:
  name: website-ticket-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: website-ticket
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: website-ticket-hpa
  namespace: default
spec:
  minReplicas: 1
  maxReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: website-ticket
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70