name: Build and Push Docker Image to Docker Hub 

on: 
  push: 
    branches: [ "main" ] 
  pull_request: 
    branches: [ "main" ] 

env: 
  REGISTRY: docker.io 
  IMAGE_NAME: ${{ secrets.asriazhari }}/website-ticket

jobs: 
  build: 
    runs-on: ubuntu-latest 

    steps: 
      - name: Check out the code
        uses: actions/checkout@v3 

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.asriazhari }}
          password: ${{ secrets.UbakeOsamawe12 }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2 
        with: 
          context: . 
          push: true 
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          
  test: 
    runs-on: ubuntu-latest 

    steps: 
      - name: Check out the code
        uses: actions/checkout@v3 

      - name: Build the Docker image
        run: docker build -t website-ticket:latest .

      - name: Run container in detached mode
        run: docker run -d -p 3000:8080 website-ticket:latest

      - name: Test the running container
        run: |
          sleep 10
          curl -f http://localhost:3000 || exit 1
